package day7

var m = map[string]map[string]struct{}{
	"bright aqua": {
		"bright cyan":    struct{}{},
		"bright green":   struct{}{},
		"clear lavender": struct{}{},
		"dim indigo":     struct{}{},
		"faded plum":     struct{}{},
		"light indigo":   struct{}{},
		"muted maroon":   struct{}{},
		"muted red":      struct{}{},
		"shiny lavender": struct{}{},
		"wavy fuchsia":   struct{}{},
		"wavy salmon":    struct{}{},
		"wavy violet":    struct{}{},
	},
	"bright beige": {
		"dark orange":  struct{}{},
		"plaid gold":   struct{}{},
		"plaid maroon": struct{}{},
	},
	"bright black": {
		"dark purple":   struct{}{},
		"dotted violet": struct{}{},
		"muted plum":    struct{}{},
		"posh red":      struct{}{},
	},
	"bright blue": {
		"bright indigo":     struct{}{},
		"bright magenta":    struct{}{},
		"dim chartreuse":    struct{}{},
		"dotted chartreuse": struct{}{},
		"dull green":        struct{}{},
		"posh gray":         struct{}{},
		"shiny plum":        struct{}{},
		"wavy crimson":      struct{}{},
	},
	"bright bronze": {
		"light plum": struct{}{},
	},
	"bright brown": {
		"pale white":   struct{}{},
		"shiny brown":  struct{}{},
		"wavy fuchsia": struct{}{},
		"wavy tomato":  struct{}{},
	},
	"bright coral": {
		"bright brown": struct{}{},
		"dull cyan":    struct{}{},
		"pale plum":    struct{}{},
		"posh crimson": struct{}{},
	},
	"bright cyan": {
		"light coral": struct{}{},
	},
	"bright fuchsia": {
		"faded tan":      struct{}{},
		"vibrant silver": struct{}{},
		"wavy cyan":      struct{}{},
	},
	"bright gold": {
		"shiny gray": struct{}{},
		"wavy olive": struct{}{},
	},
	"bright green": {
		"clear brown":    struct{}{},
		"clear lavender": struct{}{},
		"drab gold":      struct{}{},
		"drab lime":      struct{}{},
		"light white":    struct{}{},
		"pale orange":    struct{}{},
		"posh brown":     struct{}{},
	},
	"bright indigo": {
		"clear cyan":     struct{}{},
		"dark lime":      struct{}{},
		"drab gold":      struct{}{},
		"drab magenta":   struct{}{},
		"posh bronze":    struct{}{},
		"vibrant maroon": struct{}{},
		"wavy red":       struct{}{},
	},
	"bright lavender": {
		"light fuchsia": struct{}{},
		"pale lime":     struct{}{},
		"striped gold":  struct{}{},
	},
	"bright lime": {
		"dark chartreuse": struct{}{},
		"dotted magenta":  struct{}{},
		"faded fuchsia":   struct{}{},
		"shiny beige":     struct{}{},
	},
	"bright orange": {
		"clear lavender": struct{}{},
		"clear maroon":   struct{}{},
		"drab cyan":      struct{}{},
		"faded purple":   struct{}{},
		"faded violet":   struct{}{},
		"posh gray":      struct{}{},
		"striped brown":  struct{}{},
		"vibrant coral":  struct{}{},
	},
	"bright plum": {
		"bright purple": struct{}{},
	},
	"bright red": {
		"dotted coral":    struct{}{},
		"dotted teal":     struct{}{},
		"drab red":        struct{}{},
		"drab tan":        struct{}{},
		"drab tomato":     struct{}{},
		"dull plum":       struct{}{},
		"light green":     struct{}{},
		"light orange":    struct{}{},
		"mirrored salmon": struct{}{},
		"plaid yellow":    struct{}{},
		"posh olive":      struct{}{},
		"posh salmon":     struct{}{},
		"striped salmon":  struct{}{},
		"striped yellow":  struct{}{},
		"vibrant violet":  struct{}{},
	},
	"bright salmon": {
		"dotted green": struct{}{},
	},
	"bright silver": {
		"dull chartreuse":     struct{}{},
		"mirrored chartreuse": struct{}{},
		"pale beige":          struct{}{},
		"posh black":          struct{}{},
		"wavy bronze":         struct{}{},
	},
	"bright tan": {
		"shiny white":    struct{}{},
		"vibrant bronze": struct{}{},
		"wavy gold":      struct{}{},
	},
	"bright teal": {
		"dark magenta":    struct{}{},
		"dark yellow":     struct{}{},
		"muted turquoise": struct{}{},
	},
	"bright tomato": {
		"drab beige": struct{}{},
		"dull teal":  struct{}{},
	},
	"bright turquoise": {
		"faded yellow": struct{}{},
	},
	"bright violet": {
		"mirrored magenta": struct{}{},
		"posh cyan":        struct{}{},
	},
	"bright white": {
		"dark crimson": struct{}{},
	},
	"clear beige": {
		"drab magenta": struct{}{},
		"drab maroon":  struct{}{},
		"pale silver":  struct{}{},
	},
	"clear black": {
		"mirrored salmon": struct{}{},
		"striped teal":    struct{}{},
	},
	"clear bronze": {
		"dark olive":      struct{}{},
		"dim red":         struct{}{},
		"pale chartreuse": struct{}{},
	},
	"clear brown": {
		"dotted plum":   struct{}{},
		"dull red":      struct{}{},
		"light fuchsia": struct{}{},
		"plaid plum":    struct{}{},
		"vibrant red":   struct{}{},
	},
	"clear chartreuse": {
		"vibrant gold": struct{}{},
	},
	"clear crimson": {
		"muted turquoise": struct{}{},
		"pale bronze":     struct{}{},
	},
	"clear cyan": {
		"bright gray":   struct{}{},
		"dim indigo":    struct{}{},
		"dim olive":     struct{}{},
		"faded red":     struct{}{},
		"mirrored cyan": struct{}{},
		"muted green":   struct{}{},
		"muted purple":  struct{}{},
		"striped red":   struct{}{},
	},
	"clear fuchsia": {
		"muted tomato": struct{}{},
	},
	"clear gold": {
		"dim black":      struct{}{},
		"mirrored plum":  struct{}{},
		"mirrored white": struct{}{},
		"wavy cyan":      struct{}{},
		"wavy indigo":    struct{}{},
	},
	"clear gray": {
		"bright bronze": struct{}{},
		"clear aqua":    struct{}{},
		"dim lime":      struct{}{},
		"shiny cyan":    struct{}{},
	},
	"clear indigo": {
		"mirrored coral": struct{}{},
	},
	"clear lavender": {
		"plaid gold":    struct{}{},
		"plaid magenta": struct{}{},
		"striped olive": struct{}{},
		"wavy plum":     struct{}{},
	},
	"clear maroon": {
		"wavy purple": struct{}{},
	},
	"clear olive": {
		"dotted fuchsia": struct{}{},
	},
	"clear orange": {
		"wavy black": struct{}{},
	},
	"clear plum": {
		"bright turquoise": struct{}{},
		"clear salmon":     struct{}{},
		"dotted teal":      struct{}{},
		"dotted turquoise": struct{}{},
		"light bronze":     struct{}{},
		"posh green":       struct{}{},
		"posh teal":        struct{}{},
		"shiny coral":      struct{}{},
	},
	"clear purple": {
		"dim plum": struct{}{},
	},
	"clear salmon": {
		"clear silver": struct{}{},
		"muted gray":   struct{}{},
		"pale orange":  struct{}{},
	},
	"clear tan": {
		"dull white":       struct{}{},
		"muted chartreuse": struct{}{},
		"shiny brown":      struct{}{},
		"shiny purple":     struct{}{},
		"striped bronze":   struct{}{},
		"striped plum":     struct{}{},
	},
	"clear teal": {
		"faded plum":   struct{}{},
		"mirrored tan": struct{}{},
		"plaid yellow": struct{}{},
	},
	"clear tomato": {
		"dotted indigo":   struct{}{},
		"mirrored yellow": struct{}{},
	},
	"clear turquoise": {
		"drab chartreuse": struct{}{},
		"striped blue":    struct{}{},
	},
	"clear violet": {
		"clear orange": struct{}{},
		"dim maroon":   struct{}{},
	},
	"clear white": {
		"faded coral": struct{}{},
	},
	"clear yellow": {
		"plaid silver": struct{}{},
	},
	"dark aqua": {
		"drab olive": struct{}{},
		"posh coral": struct{}{},
		"posh gold":  struct{}{},
		"shiny lime": struct{}{},
	},
	"dark black": {
		"dim yellow": struct{}{},
	},
	"dark bronze": {
		"drab crimson": struct{}{},
		"dull beige":   struct{}{},
		"dull orange":  struct{}{},
		"faded orange": struct{}{},
		"posh yellow":  struct{}{},
		"wavy beige":   struct{}{},
		"wavy orange":  struct{}{},
	},
	"dark brown": {
		"bright green":    struct{}{},
		"drab chartreuse": struct{}{},
		"pale fuchsia":    struct{}{},
		"plaid indigo":    struct{}{},
		"posh lavender":   struct{}{},
		"posh salmon":     struct{}{},
		"striped green":   struct{}{},
		"striped magenta": struct{}{},
		"wavy bronze":     struct{}{},
	},
	"dark chartreuse": {
		"clear cyan":     struct{}{},
		"clear orange":   struct{}{},
		"dotted crimson": struct{}{},
		"faded indigo":   struct{}{},
		"light black":    struct{}{},
		"posh plum":      struct{}{},
	},
	"dark coral": {
		"plaid fuchsia": struct{}{},
		"striped gold":  struct{}{},
		"wavy lime":     struct{}{},
	},
	"dark cyan": {
		"dark silver":    struct{}{},
		"mirrored beige": struct{}{},
	},
	"dark fuchsia": {
		"mirrored turquoise": struct{}{},
	},
	"dark gray": {
		"dull gray":   struct{}{},
		"posh green":  struct{}{},
		"wavy yellow": struct{}{},
	},
	"dark indigo": {
		"dull gold":    struct{}{},
		"faded lime":   struct{}{},
		"faded maroon": struct{}{},
	},
	"dark lavender": {
		"pale aqua":      struct{}{},
		"vibrant maroon": struct{}{},
	},
	"dark olive": {
		"drab salmon": struct{}{},
		"light teal":  struct{}{},
	},
	"dark orange": {
		"clear chartreuse": struct{}{},
		"dull blue":        struct{}{},
		"dull red":         struct{}{},
		"posh bronze":      struct{}{},
		"wavy bronze":      struct{}{},
	},
	"dark purple": {
		"dotted brown": struct{}{},
	},
	"dark salmon": {
		"dull aqua": struct{}{},
	},
	"dark silver": {
		"bright teal":    struct{}{},
		"drab aqua":      struct{}{},
		"faded yellow":   struct{}{},
		"light salmon":   struct{}{},
		"mirrored red":   struct{}{},
		"vibrant tomato": struct{}{},
	},
	"dark tan": {
		"pale turquoise": struct{}{},
		"plaid teal":     struct{}{},
		"posh gold":      struct{}{},
	},
	"dark tomato": {
		"dull yellow":  struct{}{},
		"shiny plum":   struct{}{},
		"vibrant blue": struct{}{},
	},
	"dark violet": {
		"dim magenta":      struct{}{},
		"dotted turquoise": struct{}{},
		"pale crimson":     struct{}{},
		"posh bronze":      struct{}{},
		"shiny olive":      struct{}{},
	},
	"dark white": {
		"bright cyan":     struct{}{},
		"clear teal":      struct{}{},
		"drab cyan":       struct{}{},
		"faded turquoise": struct{}{},
		"light orange":    struct{}{},
		"shiny aqua":      struct{}{},
		"shiny gold":      struct{}{},
		"striped cyan":    struct{}{},
	},
	"dark yellow": {
		"wavy aqua": struct{}{},
	},
	"dim aqua": {
		"bright plum":   struct{}{},
		"dotted tan":    struct{}{},
		"dull tomato":   struct{}{},
		"pale yellow":   struct{}{},
		"posh coral":    struct{}{},
		"posh violet":   struct{}{},
		"striped coral": struct{}{},
	},
	"dim black": {
		"dull violet":    struct{}{},
		"vibrant indigo": struct{}{},
	},
	"dim blue": {
		"vibrant indigo": struct{}{},
	},
	"dim chartreuse": {
		"clear crimson":    struct{}{},
		"dark cyan":        struct{}{},
		"light orange":     struct{}{},
		"muted maroon":     struct{}{},
		"pale tomato":      struct{}{},
		"plaid chartreuse": struct{}{},
		"striped olive":    struct{}{},
	},
	"dim coral": {
		"clear plum":       struct{}{},
		"drab indigo":      struct{}{},
		"faded chartreuse": struct{}{},
		"plaid chartreuse": struct{}{},
		"plaid salmon":     struct{}{},
	},
	"dim crimson": {
		"dotted green":  struct{}{},
		"faded magenta": struct{}{},
		"plaid tan":     struct{}{},
	},
	"dim cyan": {
		"dark green": struct{}{},
	},
	"dim fuchsia": {
		"clear blue": struct{}{},
	},
	"dim gray": {
		"posh purple": struct{}{},
	},
	"dim green": {
		"bright gray":     struct{}{},
		"dark bronze":     struct{}{},
		"muted bronze":    struct{}{},
		"pale gray":       struct{}{},
		"plaid olive":     struct{}{},
		"shiny silver":    struct{}{},
		"vibrant magenta": struct{}{},
	},
	"dim indigo": {
		"dim bronze":     struct{}{},
		"mirrored gray":  struct{}{},
		"muted blue":     struct{}{},
		"striped purple": struct{}{},
	},
	"dim magenta": {
		"clear lime":      struct{}{},
		"mirrored purple": struct{}{},
	},
	"dim olive": {
		"dim gold": struct{}{},
	},
	"dim red": {
		"plaid cyan": struct{}{},
	},
	"dim silver": {
		"dark black":      struct{}{},
		"light violet":    struct{}{},
		"mirrored violet": struct{}{},
	},
	"dim teal": {
		"bright silver":     struct{}{},
		"dark orange":       struct{}{},
		"dark white":        struct{}{},
		"dotted purple":     struct{}{},
		"drab silver":       struct{}{},
		"drab tomato":       struct{}{},
		"dull coral":        struct{}{},
		"muted silver":      struct{}{},
		"pale tomato":       struct{}{},
		"posh black":        struct{}{},
		"posh chartreuse":   struct{}{},
		"shiny yellow":      struct{}{},
		"striped gold":      struct{}{},
		"striped tan":       struct{}{},
		"striped violet":    struct{}{},
		"vibrant turquoise": struct{}{},
	},
	"dim tomato": {
		"dim bronze":   struct{}{},
		"mirrored tan": struct{}{},
	},
	"dim turquoise": {
		"faded lime":         struct{}{},
		"light olive":        struct{}{},
		"mirrored turquoise": struct{}{},
	},
	"dim white": {
		"vibrant indigo": struct{}{},
		"wavy turquoise": struct{}{},
	},
	"dotted bronze": {
		"dotted olive":   struct{}{},
		"light tomato":   struct{}{},
		"mirrored white": struct{}{},
	},
	"dotted brown": {
		"dark magenta": struct{}{},
		"plaid silver": struct{}{},
	},
	"dotted chartreuse": {
		"bright purple":   struct{}{},
		"dotted coral":    struct{}{},
		"drab black":      struct{}{},
		"mirrored tomato": struct{}{},
		"muted black":     struct{}{},
		"muted coral":     struct{}{},
		"pale tan":        struct{}{},
	},
	"dotted coral": {
		"dull aqua":      struct{}{},
		"posh indigo":    struct{}{},
		"striped orange": struct{}{},
	},
	"dotted cyan": {
		"clear gray": struct{}{},
	},
	"dotted fuchsia": {
		"pale plum":       struct{}{},
		"plaid cyan":      struct{}{},
		"striped blue":    struct{}{},
		"vibrant crimson": struct{}{},
	},
	"dotted gold": {
		"bright yellow": struct{}{},
		"light tomato":  struct{}{},
	},
	"dotted gray": {
		"mirrored yellow": struct{}{},
		"wavy turquoise":  struct{}{},
	},
	"dotted green": {
		"drab yellow": struct{}{},
		"plaid coral": struct{}{},
	},
	"dotted indigo": {
		"dark gold":   struct{}{},
		"drab salmon": struct{}{},
	},
	"dotted lavender": {
		"light silver": struct{}{},
		"pale indigo":  struct{}{},
	},
	"dotted lime": {
		"dull chartreuse": struct{}{},
		"mirrored green":  struct{}{},
		"plaid plum":      struct{}{},
	},
	"dotted magenta": {
		"dark cyan":      struct{}{},
		"mirrored brown": struct{}{},
		"muted brown":    struct{}{},
		"posh beige":     struct{}{},
	},
	"dotted maroon": {
		"dull lavender": struct{}{},
	},
	"dotted olive": {
		"dull fuchsia":  struct{}{},
		"faded crimson": struct{}{},
		"light beige":   struct{}{},
		"mirrored tan":  struct{}{},
		"pale teal":     struct{}{},
		"posh fuchsia":  struct{}{},
		"posh gold":     struct{}{},
	},
	"dotted purple": {
		"faded gold":       struct{}{},
		"mirrored aqua":    struct{}{},
		"posh bronze":      struct{}{},
		"shiny chartreuse": struct{}{},
	},
	"dotted salmon": {
		"clear red": struct{}{},
	},
	"dotted silver": {
		"clear red":    struct{}{},
		"dark gold":    struct{}{},
		"muted blue":   struct{}{},
		"muted yellow": struct{}{},
		"posh white":   struct{}{},
	},
	"dotted tan": {
		"dull indigo":     struct{}{},
		"light turquoise": struct{}{},
	},
	"dotted teal": {
		"dark purple":     struct{}{},
		"muted indigo":    struct{}{},
		"plaid turquoise": struct{}{},
		"striped black":   struct{}{},
		"vibrant silver":  struct{}{},
	},
	"dotted tomato": {
		"drab brown":   struct{}{},
		"muted plum":   struct{}{},
		"shiny violet": struct{}{},
	},
	"dotted turquoise": {
		"dark lime":    struct{}{},
		"dotted olive": struct{}{},
		"drab yellow":  struct{}{},
		"plaid lime":   struct{}{},
		"posh plum":    struct{}{},
		"striped tan":  struct{}{},
		"vibrant teal": struct{}{},
		"wavy olive":   struct{}{},
	},
	"dotted white": {
		"wavy silver": struct{}{},
	},
	"drab beige": {
		"striped plum": struct{}{},
	},
	"drab black": {
		"dull lavender": struct{}{},
	},
	"drab blue": {
		"mirrored cyan": struct{}{},
		"posh beige":    struct{}{},
		"wavy green":    struct{}{},
	},
	"drab bronze": {
		"light plum": struct{}{},
	},
	"drab coral": {
		"dark salmon":  struct{}{},
		"shiny violet": struct{}{},
	},
	"drab crimson": {
		"dark magenta":   struct{}{},
		"drab lavender":  struct{}{},
		"dull white":     struct{}{},
		"mirrored coral": struct{}{},
		"wavy brown":     struct{}{},
	},
	"drab cyan": {
		"clear brown":      struct{}{},
		"dark tomato":      struct{}{},
		"drab lavender":    struct{}{},
		"drab lime":        struct{}{},
		"drab magenta":     struct{}{},
		"light chartreuse": struct{}{},
		"pale tomato":      struct{}{},
		"wavy teal":        struct{}{},
	},
	"drab gold": {
		"bright magenta":   struct{}{},
		"clear turquoise":  struct{}{},
		"dim tomato":       struct{}{},
		"mirrored cyan":    struct{}{},
		"muted tan":        struct{}{},
		"plaid silver":     struct{}{},
		"vibrant lavender": struct{}{},
	},
	"drab green": {
		"bright white": struct{}{},
		"dim brown":    struct{}{},
		"dotted brown": struct{}{},
		"drab indigo":  struct{}{},
		"plaid aqua":   struct{}{},
		"striped red":  struct{}{},
	},
	"drab indigo": {
		"clear gold":    struct{}{},
		"clear silver":  struct{}{},
		"clear white":   struct{}{},
		"dotted beige":  struct{}{},
		"plaid bronze":  struct{}{},
		"shiny fuchsia": struct{}{},
		"wavy aqua":     struct{}{},
	},
	"drab lavender": {
		"dark indigo":      struct{}{},
		"drab lime":        struct{}{},
		"faded beige":      struct{}{},
		"mirrored magenta": struct{}{},
		"striped bronze":   struct{}{},
		"vibrant silver":   struct{}{},
	},
	"drab lime": {
		"posh aqua":   struct{}{},
		"striped tan": struct{}{},
		"wavy white":  struct{}{},
	},
	"drab magenta": {
		"clear lime": struct{}{},
		"posh tan":   struct{}{},
	},
	"drab maroon": {
		"dark lime": struct{}{},
	},
	"drab olive": {
		"bright violet":  struct{}{},
		"vibrant silver": struct{}{},
		"wavy turquoise": struct{}{},
	},
	"drab orange": {
		"vibrant red": struct{}{},
	},
	"drab plum": {
		"dark olive":  struct{}{},
		"faded olive": struct{}{},
	},
	"drab purple": {
		"dim cyan":   struct{}{},
		"dim purple": struct{}{},
	},
	"drab red": {
		"bright beige":   struct{}{},
		"bright olive":   struct{}{},
		"bright salmon":  struct{}{},
		"dark lavender":  struct{}{},
		"drab turquoise": struct{}{},
		"faded beige":    struct{}{},
		"muted tomato":   struct{}{},
		"striped cyan":   struct{}{},
		"vibrant white":  struct{}{},
	},
	"drab salmon": {
		"drab chartreuse": struct{}{},
	},
	"drab silver": {
		"clear aqua":       struct{}{},
		"dotted orange":    struct{}{},
		"faded crimson":    struct{}{},
		"mirrored silver":  struct{}{},
		"plaid chartreuse": struct{}{},
		"shiny magenta":    struct{}{},
	},
	"drab tan": {
		"bright brown":   struct{}{},
		"dark salmon":    struct{}{},
		"muted salmon":   struct{}{},
		"pale plum":      struct{}{},
		"striped tomato": struct{}{},
		"vibrant teal":   struct{}{},
	},
	"drab teal": {
		"bright tan": struct{}{},
		"drab cyan":  struct{}{},
	},
	"drab tomato": {
		"clear turquoise": struct{}{},
		"dark orange":     struct{}{},
		"faded black":     struct{}{},
		"mirrored white":  struct{}{},
		"striped silver":  struct{}{},
		"vibrant bronze":  struct{}{},
	},
	"drab turquoise": {
		"dark lavender": struct{}{},
		"dark maroon":   struct{}{},
		"faded coral":   struct{}{},
		"pale teal":     struct{}{},
		"plaid white":   struct{}{},
		"shiny salmon":  struct{}{},
	},
	"drab violet": {
		"plaid violet": struct{}{},
		"posh white":   struct{}{},
	},
	"drab white": {
		"light olive": struct{}{},
	},
	"dull beige": {
		"clear orange":  struct{}{},
		"dark indigo":   struct{}{},
		"dotted salmon": struct{}{},
		"muted aqua":    struct{}{},
		"shiny tomato":  struct{}{},
	},
	"dull blue": {
		"clear salmon":    struct{}{},
		"mirrored maroon": struct{}{},
		"muted beige":     struct{}{},
		"wavy blue":       struct{}{},
		"wavy green":      struct{}{},
	},
	"dull bronze": {
		"striped blue": struct{}{},
	},
	"dull brown": {
		"shiny tan": struct{}{},
	},
	"dull chartreuse": {
		"shiny red": struct{}{},
	},
	"dull coral": {
		"clear beige":  struct{}{},
		"clear indigo": struct{}{},
		"dark tomato":  struct{}{},
		"dim coral":    struct{}{},
		"dotted teal":  struct{}{},
		"dull indigo":  struct{}{},
		"faded red":    struct{}{},
		"muted brown":  struct{}{},
		"muted orange": struct{}{},
		"plaid gray":   struct{}{},
		"wavy crimson": struct{}{},
		"wavy violet":  struct{}{},
	},
	"dull crimson": {
		"bright olive": struct{}{},
		"bright plum":  struct{}{},
	},
	"dull cyan": {
		"dotted lavender": struct{}{},
		"dull crimson":    struct{}{},
		"dull lavender":   struct{}{},
		"faded white":     struct{}{},
	},
	"dull fuchsia": {
		"dotted gold":   struct{}{},
		"drab white":    struct{}{},
		"plaid crimson": struct{}{},
	},
	"dull gold": {
		"clear blue":  struct{}{},
		"light olive": struct{}{},
	},
	"dull green": {
		"faded indigo":   struct{}{},
		"mirrored beige": struct{}{},
		"plaid beige":    struct{}{},
		"plaid orange":   struct{}{},
	},
	"dull indigo": {
		"faded magenta": struct{}{},
	},
	"dull lavender": {
		"light maroon": struct{}{},
		"posh green":   struct{}{},
	},
	"dull magenta": {
		"clear white":        struct{}{},
		"dim teal":           struct{}{},
		"dim white":          struct{}{},
		"dull maroon":        struct{}{},
		"dull plum":          struct{}{},
		"muted green":        struct{}{},
		"muted orange":       struct{}{},
		"muted red":          struct{}{},
		"pale salmon":        struct{}{},
		"plaid lavender":     struct{}{},
		"posh crimson":       struct{}{},
		"shiny beige":        struct{}{},
		"shiny gold":         struct{}{},
		"striped chartreuse": struct{}{},
	},
	"dull maroon": {
		"bright green":    struct{}{},
		"dark red":        struct{}{},
		"dotted magenta":  struct{}{},
		"light crimson":   struct{}{},
		"mirrored brown":  struct{}{},
		"mirrored yellow": struct{}{},
		"muted gold":      struct{}{},
		"posh blue":       struct{}{},
		"posh plum":       struct{}{},
		"shiny green":     struct{}{},
		"striped yellow":  struct{}{},
	},
	"dull olive": {
		"dim orange":  struct{}{},
		"light beige": struct{}{},
		"muted white": struct{}{},
	},
	"dull orange": {
		"bright fuchsia": struct{}{},
		"vibrant gold":   struct{}{},
	},
	"dull plum": {
		"dark red":         struct{}{},
		"dark turquoise":   struct{}{},
		"light chartreuse": struct{}{},
		"mirrored olive":   struct{}{},
		"vibrant tan":      struct{}{},
		"wavy beige":       struct{}{},
	},
	"dull red": {
		"dark aqua":       struct{}{},
		"dull chartreuse": struct{}{},
		"dull green":      struct{}{},
		"mirrored red":    struct{}{},
		"muted aqua":      struct{}{},
		"plaid plum":      struct{}{},
		"posh maroon":     struct{}{},
		"shiny silver":    struct{}{},
		"shiny turquoise": struct{}{},
		"striped aqua":    struct{}{},
	},
	"dull salmon": {
		"light turquoise": struct{}{},
		"muted maroon":    struct{}{},
		"posh turquoise":  struct{}{},
		"wavy maroon":     struct{}{},
	},
	"dull silver": {
		"bright beige":   struct{}{},
		"bright red":     struct{}{},
		"clear lavender": struct{}{},
		"dotted maroon":  struct{}{},
		"dull maroon":    struct{}{},
		"faded violet":   struct{}{},
		"muted teal":     struct{}{},
		"plaid lavender": struct{}{},
		"shiny beige":    struct{}{},
		"striped gold":   struct{}{},
		"wavy olive":     struct{}{},
	},
	"dull tan": {
		"dark coral":    struct{}{},
		"dark salmon":   struct{}{},
		"dim aqua":      struct{}{},
		"drab crimson":  struct{}{},
		"dull beige":    struct{}{},
		"dull maroon":   struct{}{},
		"faded violet":  struct{}{},
		"mirrored lime": struct{}{},
		"muted fuchsia": struct{}{},
		"muted gold":    struct{}{},
		"muted red":     struct{}{},
		"pale violet":   struct{}{},
		"posh aqua":     struct{}{},
		"shiny blue":    struct{}{},
	},
	"dull teal": {
		"clear red": struct{}{},
	},
	"dull tomato": {
		"dim indigo": struct{}{},
	},
	"dull turquoise": {
		"faded green": struct{}{},
	},
	"dull white": {
		"light blue": struct{}{},
	},
	"faded aqua": {
		"drab gray":  struct{}{},
		"muted gray": struct{}{},
	},
	"faded beige": {
		"dark lavender":    struct{}{},
		"mirrored fuchsia": struct{}{},
		"muted turquoise":  struct{}{},
	},
	"faded black": {
		"clear plum": struct{}{},
		"pale gray":  struct{}{},
	},
	"faded bronze": {
		"dull coral":    struct{}{},
		"muted gold":    struct{}{},
		"wavy lavender": struct{}{},
	},
	"faded brown": {
		"dim gray":    struct{}{},
		"posh purple": struct{}{},
		"wavy plum":   struct{}{},
	},
	"faded chartreuse": {
		"plaid tomato": struct{}{},
	},
	"faded crimson": {
		"drab fuchsia": struct{}{},
	},
	"faded cyan": {
		"dim chartreuse": struct{}{},
		"dotted magenta": struct{}{},
		"drab silver":    struct{}{},
		"dull maroon":    struct{}{},
		"dull tan":       struct{}{},
		"faded bronze":   struct{}{},
		"light indigo":   struct{}{},
		"muted black":    struct{}{},
		"shiny brown":    struct{}{},
		"vibrant black":  struct{}{},
		"vibrant blue":   struct{}{},
	},
	"faded fuchsia": {
		"light orange":    struct{}{},
		"mirrored bronze": struct{}{},
		"plaid red":       struct{}{},
		"shiny crimson":   struct{}{},
	},
	"faded gold": {
		"faded yellow": struct{}{},
	},
	"faded gray": {
		"dark tan":        struct{}{},
		"dim salmon":      struct{}{},
		"pale red":        struct{}{},
		"shiny turquoise": struct{}{},
		"striped crimson": struct{}{},
		"wavy tan":        struct{}{},
	},
	"faded indigo": {
		"muted maroon": struct{}{},
	},
	"faded lavender": {
		"dark gray":    struct{}{},
		"vibrant aqua": struct{}{},
	},
	"faded lime": {
		"muted orange": struct{}{},
	},
	"faded maroon": {
		"clear red":    struct{}{},
		"dark magenta": struct{}{},
	},
	"faded orange": {
		"light beige":    struct{}{},
		"vibrant purple": struct{}{},
	},
	"faded purple": {
		"dark crimson": struct{}{},
		"drab maroon":  struct{}{},
	},
	"faded red": {
		"drab violet":      struct{}{},
		"dull tomato":      struct{}{},
		"vibrant lavender": struct{}{},
		"wavy yellow":      struct{}{},
	},
	"faded tomato": {
		"drab black":  struct{}{},
		"light black": struct{}{},
		"shiny teal":  struct{}{},
	},
	"faded turquoise": {
		"clear olive":    struct{}{},
		"dotted fuchsia": struct{}{},
		"faded brown":    struct{}{},
		"muted yellow":   struct{}{},
		"plaid olive":    struct{}{},
		"shiny gold":     struct{}{},
	},
	"faded violet": {
		"bright blue":    struct{}{},
		"dim crimson":    struct{}{},
		"faded purple":   struct{}{},
		"mirrored aqua":  struct{}{},
		"mirrored brown": struct{}{},
		"posh indigo":    struct{}{},
	},
	"faded white": {
		"plaid tomato": struct{}{},
	},
	"light aqua": {
		"bright blue":     struct{}{},
		"dark white":      struct{}{},
		"drab cyan":       struct{}{},
		"mirrored cyan":   struct{}{},
		"mirrored tomato": struct{}{},
		"pale brown":      struct{}{},
		"plaid indigo":    struct{}{},
		"posh chartreuse": struct{}{},
		"striped plum":    struct{}{},
		"striped salmon":  struct{}{},
	},
	"light beige": {
		"plaid coral": struct{}{},
	},
	"light black": {
		"clear black": struct{}{},
		"dull cyan":   struct{}{},
		"light tan":   struct{}{},
	},
	"light blue": {
		"bright tan":     struct{}{},
		"dotted red":     struct{}{},
		"dull violet":    struct{}{},
		"faded olive":    struct{}{},
		"striped tomato": struct{}{},
	},
	"light bronze": {
		"dim maroon": struct{}{},
		"wavy cyan":  struct{}{},
	},
	"light brown": {
		"clear gold": struct{}{},
		"dim plum":   struct{}{},
	},
	"light chartreuse": {
		"dark cyan":      struct{}{},
		"muted violet":   struct{}{},
		"pale green":     struct{}{},
		"vibrant orange": struct{}{},
		"vibrant yellow": struct{}{},
	},
	"light crimson": {
		"bright cyan":    struct{}{},
		"clear crimson":  struct{}{},
		"clear violet":   struct{}{},
		"drab teal":      struct{}{},
		"dull blue":      struct{}{},
		"pale salmon":    struct{}{},
		"plaid orange":   struct{}{},
		"plaid red":      struct{}{},
		"posh yellow":    struct{}{},
		"striped orange": struct{}{},
	},
	"light gray": {
		"dotted aqua": struct{}{},
		"dull indigo": struct{}{},
		"dull purple": struct{}{},
	},
	"light green": {
		"drab gray":       struct{}{},
		"drab tan":        struct{}{},
		"mirrored salmon": struct{}{},
		"muted lavender":  struct{}{},
		"plaid indigo":    struct{}{},
		"shiny bronze":    struct{}{},
		"shiny crimson":   struct{}{},
	},
	"light indigo": {
		"dull blue":   struct{}{},
		"dull gray":   struct{}{},
		"dull salmon": struct{}{},
		"wavy yellow": struct{}{},
	},
	"light lavender": {
		"dim olive":      struct{}{},
		"dull black":     struct{}{},
		"dull turquoise": struct{}{},
		"pale blue":      struct{}{},
		"striped blue":   struct{}{},
	},
	"light lime": {
		"bright blue":     struct{}{},
		"clear brown":     struct{}{},
		"clear indigo":    struct{}{},
		"dim green":       struct{}{},
		"dull blue":       struct{}{},
		"dull brown":      struct{}{},
		"faded fuchsia":   struct{}{},
		"faded turquoise": struct{}{},
		"plaid purple":    struct{}{},
		"wavy lavender":   struct{}{},
	},
	"light orange": {
		"dotted bronze": struct{}{},
		"wavy fuchsia":  struct{}{},
	},
	"light purple": {
		"bright silver":     struct{}{},
		"dark brown":        struct{}{},
		"dark violet":       struct{}{},
		"dark white":        struct{}{},
		"dim gray":          struct{}{},
		"dim teal":          struct{}{},
		"dotted aqua":       struct{}{},
		"dull tan":          struct{}{},
		"mirrored lavender": struct{}{},
		"muted yellow":      struct{}{},
		"plaid chartreuse":  struct{}{},
		"plaid indigo":      struct{}{},
		"wavy crimson":      struct{}{},
	},
	"light salmon": {
		"mirrored coral":  struct{}{},
		"mirrored violet": struct{}{},
	},
	"light silver": {
		"dim bronze": struct{}{},
	},
	"light tan": {
		"striped lime": struct{}{},
	},
	"light teal": {
		"bright maroon": struct{}{},
	},
	"light tomato": {
		"mirrored indigo": struct{}{},
	},
	"light turquoise": {
		"dotted salmon": struct{}{},
	},
	"light violet": {
		"bright chartreuse": struct{}{},
	},
	"light white": {
		"mirrored lavender": struct{}{},
	},
	"light yellow": {
		"light teal": struct{}{},
	},
	"mirrored aqua": {
		"bright turquoise": struct{}{},
		"dotted black":     struct{}{},
		"dull cyan":        struct{}{},
		"mirrored teal":    struct{}{},
		"muted bronze":     struct{}{},
	},
	"mirrored beige": {
		"dull bronze":  struct{}{},
		"pale indigo":  struct{}{},
		"pale white":   struct{}{},
		"posh fuchsia": struct{}{},
	},
	"mirrored black": {
		"dark indigo":  struct{}{},
		"posh magenta": struct{}{},
	},
	"mirrored blue": {
		"drab blue": struct{}{},
	},
	"mirrored bronze": {
		"dim cyan":         struct{}{},
		"faded chartreuse": struct{}{},
		"light violet":     struct{}{},
		"wavy indigo":      struct{}{},
		"wavy maroon":      struct{}{},
	},
	"mirrored brown": {
		"clear plum":     struct{}{},
		"dim fuchsia":    struct{}{},
		"dull orange":    struct{}{},
		"dull turquoise": struct{}{},
		"faded tan":      struct{}{},
		"light brown":    struct{}{},
		"plaid magenta":  struct{}{},
	},
	"mirrored crimson": {
		"faded green": struct{}{},
	},
	"mirrored cyan": {
		"bright white": struct{}{},
		"dim fuchsia":  struct{}{},
		"faded silver": struct{}{},
	},
	"mirrored fuchsia": {
		"dotted white":   struct{}{},
		"striped violet": struct{}{},
	},
	"mirrored gold": {
		"pale black": struct{}{},
	},
	"mirrored green": {
		"faded coral": struct{}{},
		"wavy purple": struct{}{},
	},
	"mirrored lime": {
		"dotted aqua":   struct{}{},
		"dotted tomato": struct{}{},
		"drab blue":     struct{}{},
		"shiny olive":   struct{}{},
	},
	"mirrored magenta": {
		"bright magenta":   struct{}{},
		"faded indigo":     struct{}{},
		"mirrored crimson": struct{}{},
	},
	"mirrored maroon": {
		"plaid tomato":   struct{}{},
		"vibrant maroon": struct{}{},
	},
	"mirrored olive": {
		"bright violet": struct{}{},
		"clear green":   struct{}{},
		"dim brown":     struct{}{},
		"dotted orange": struct{}{},
		"mirrored red":  struct{}{},
	},
	"mirrored plum": {
		"plaid green": struct{}{},
	},
	"mirrored salmon": {
		"drab fuchsia": struct{}{},
		"wavy cyan":    struct{}{},
	},
	"mirrored silver": {
		"light cyan": struct{}{},
		"wavy beige": struct{}{},
	},
	"mirrored tan": {
		"plaid green": struct{}{},
	},
	"mirrored teal": {
		"bright gray":   struct{}{},
		"plaid crimson": struct{}{},
		"posh tomato":   struct{}{},
	},
	"mirrored tomato": {
		"clear tomato":        struct{}{},
		"light cyan":          struct{}{},
		"mirrored chartreuse": struct{}{},
		"mirrored tan":        struct{}{},
		"plaid green":         struct{}{},
	},
	"mirrored turquoise": {
		"light maroon": struct{}{},
	},
	"mirrored white": {
		"dotted white":  struct{}{},
		"drab gray":     struct{}{},
		"faded teal":    struct{}{},
		"mirrored gold": struct{}{},
		"posh yellow":   struct{}{},
	},
	"mirrored yellow": {
		"bright maroon": struct{}{},
	},
	"muted blue": {
		"bright crimson": struct{}{},
		"bright tomato":  struct{}{},
	},
	"muted bronze": {
		"clear fuchsia": struct{}{},
		"muted silver":  struct{}{},
		"shiny gray":    struct{}{},
	},
	"muted brown": {
		"drab plum":     struct{}{},
		"dull lavender": struct{}{},
		"faded aqua":    struct{}{},
	},
	"muted chartreuse": {
		"clear magenta": struct{}{},
		"drab salmon":   struct{}{},
		"dull lime":     struct{}{},
		"muted indigo":  struct{}{},
		"shiny coral":   struct{}{},
		"vibrant plum":  struct{}{},
	},
	"muted coral": {
		"clear black": struct{}{},
		"pale tomato": struct{}{},
		"posh beige":  struct{}{},
	},
	"muted crimson": {
		"dotted white": struct{}{},
	},
	"muted cyan": {
		"plaid aqua": struct{}{},
	},
	"muted fuchsia": {
		"bright lavender": struct{}{},
		"clear black":     struct{}{},
		"dark teal":       struct{}{},
		"dark white":      struct{}{},
		"dim aqua":        struct{}{},
		"faded black":     struct{}{},
		"faded tan":       struct{}{},
	},
	"muted gold": {
		"dim chartreuse":   struct{}{},
		"dotted turquoise": struct{}{},
		"light crimson":    struct{}{},
		"mirrored fuchsia": struct{}{},
		"pale blue":        struct{}{},
		"plaid blue":       struct{}{},
		"posh turquoise":   struct{}{},
		"shiny magenta":    struct{}{},
		"wavy lavender":    struct{}{},
	},
	"muted gray": {
		"wavy gray": struct{}{},
	},
	"muted indigo": {
		"clear tomato":      struct{}{},
		"dotted plum":       struct{}{},
		"plaid violet":      struct{}{},
		"striped turquoise": struct{}{},
	},
	"muted magenta": {
		"clear white": struct{}{},
		"muted olive": struct{}{},
		"shiny blue":  struct{}{},
	},
	"muted olive": {
		"dim brown":      struct{}{},
		"vibrant salmon": struct{}{},
	},
	"muted plum": {
		"dark red":  struct{}{},
		"drab plum": struct{}{},
	},
	"muted purple": {
		"dark gray":     struct{}{},
		"dotted blue":   struct{}{},
		"drab lavender": struct{}{},
		"dull fuchsia":  struct{}{},
		"faded crimson": struct{}{},
		"shiny orange":  struct{}{},
		"wavy black":    struct{}{},
	},
	"muted red": {
		"bright salmon": struct{}{},
		"faded bronze":  struct{}{},
		"faded tomato":  struct{}{},
		"muted crimson": struct{}{},
		"vibrant brown": struct{}{},
		"wavy lavender": struct{}{},
	},
	"muted silver": {
		"bright bronze": struct{}{},
		"faded lime":    struct{}{},
		"light coral":   struct{}{},
		"wavy magenta":  struct{}{},
	},
	"muted tan": {
		"dim lavender":   struct{}{},
		"muted lime":     struct{}{},
		"striped orange": struct{}{},
	},
	"muted teal": {
		"plaid maroon": struct{}{},
	},
	"muted turquoise": {
		"plaid violet":    struct{}{},
		"shiny turquoise": struct{}{},
	},
	"muted violet": {
		"dim black":      struct{}{},
		"dull bronze":    struct{}{},
		"light lavender": struct{}{},
		"shiny coral":    struct{}{},
		"shiny teal":     struct{}{},
	},
	"muted white": {
		"dim purple": struct{}{},
	},
	"muted yellow": {
		"light maroon": struct{}{},
	},
	"no other bags": {
		"bright aqua":   struct{}{},
		"bright lime":   struct{}{},
		"bright orange": struct{}{},
		"dull magenta":  struct{}{},
		"dull silver":   struct{}{},
		"faded cyan":    struct{}{},
		"faded gray":    struct{}{},
		"light purple":  struct{}{},
		"shiny indigo":  struct{}{},
		"wavy coral":    struct{}{},
	},
	"pale aqua": {
		"faded olive": struct{}{},
	},
	"pale beige": {
		"plaid aqua": struct{}{},
	},
	"pale black": {
		"wavy purple": struct{}{},
	},
	"pale blue": {
		"plaid red": struct{}{},
	},
	"pale bronze": {
		"bright bronze": struct{}{},
		"pale maroon":   struct{}{},
		"wavy magenta":  struct{}{},
	},
	"pale coral": {
		"clear blue":    struct{}{},
		"dim silver":    struct{}{},
		"shiny tomato":  struct{}{},
		"striped teal":  struct{}{},
		"striped white": struct{}{},
		"wavy green":    struct{}{},
	},
	"pale crimson": {
		"drab lime":      struct{}{},
		"shiny cyan":     struct{}{},
		"striped bronze": struct{}{},
		"vibrant maroon": struct{}{},
	},
	"pale cyan": {
		"dark yellow":    struct{}{},
		"light maroon":   struct{}{},
		"mirrored green": struct{}{},
	},
	"pale gold": {
		"bright tan":  struct{}{},
		"dull orange": struct{}{},
	},
	"pale green": {
		"mirrored plum": struct{}{},
	},
	"pale indigo": {
		"plaid green": struct{}{},
	},
	"pale lime": {
		"plaid teal": struct{}{},
	},
	"pale olive": {
		"dark yellow": struct{}{},
	},
	"pale orange": {
		"faded green": struct{}{},
	},
	"pale plum": {
		"clear white":  struct{}{},
		"drab fuchsia": struct{}{},
		"light gold":   struct{}{},
		"posh orange":  struct{}{},
		"wavy magenta": struct{}{},
	},
	"pale red": {
		"dotted olive": struct{}{},
		"drab beige":   struct{}{},
		"light coral":  struct{}{},
		"light gray":   struct{}{},
		"light violet": struct{}{},
	},
	"pale salmon": {
		"dull red":      struct{}{},
		"light magenta": struct{}{},
	},
	"pale tan": {
		"dim yellow":  struct{}{},
		"dull yellow": struct{}{},
		"muted black": struct{}{},
	},
	"pale teal": {
		"vibrant beige": struct{}{},
	},
	"pale tomato": {
		"clear blue": struct{}{},
		"shiny red":  struct{}{},
	},
	"pale violet": {
		"bright beige":     struct{}{},
		"dim turquoise":    struct{}{},
		"drab beige":       struct{}{},
		"faded fuchsia":    struct{}{},
		"mirrored magenta": struct{}{},
		"muted magenta":    struct{}{},
		"muted teal":       struct{}{},
		"posh silver":      struct{}{},
	},
	"pale yellow": {
		"clear brown":   struct{}{},
		"clear cyan":    struct{}{},
		"dotted lime":   struct{}{},
		"dotted olive":  struct{}{},
		"muted crimson": struct{}{},
		"plaid maroon":  struct{}{},
		"posh coral":    struct{}{},
	},
	"plaid aqua": {
		"faded magenta": struct{}{},
	},
	"plaid beige": {
		"clear bronze":     struct{}{},
		"dark fuchsia":     struct{}{},
		"shiny chartreuse": struct{}{},
		"striped black":    struct{}{},
	},
	"plaid blue": {
		"dull red":       struct{}{},
		"posh coral":     struct{}{},
		"striped orange": struct{}{},
	},
	"plaid bronze": {
		"dull turquoise": struct{}{},
	},
	"plaid chartreuse": {
		"dark fuchsia":   struct{}{},
		"faded red":      struct{}{},
		"mirrored black": struct{}{},
		"plaid orange":   struct{}{},
		"shiny black":    struct{}{},
	},
	"plaid fuchsia": {
		"pale plum":  struct{}{},
		"plaid cyan": struct{}{},
	},
	"plaid gold": {
		"dull salmon":  struct{}{},
		"shiny silver": struct{}{},
	},
	"plaid gray": {
		"dotted green": struct{}{},
	},
	"plaid indigo": {
		"bright coral":   struct{}{},
		"dark blue":      struct{}{},
		"dotted magenta": struct{}{},
		"light lime":     struct{}{},
		"striped olive":  struct{}{},
		"wavy yellow":    struct{}{},
	},
	"plaid lavender": {
		"bright salmon": struct{}{},
		"dim teal":      struct{}{},
		"light aqua":    struct{}{},
		"pale crimson":  struct{}{},
		"vibrant white": struct{}{},
	},
	"plaid lime": {
		"bright yellow": struct{}{},
		"pale olive":    struct{}{},
		"shiny silver":  struct{}{},
		"wavy white":    struct{}{},
	},
	"plaid magenta": {
		"dark black":    struct{}{},
		"pale lavender": struct{}{},
	},
	"plaid maroon": {
		"drab bronze":   struct{}{},
		"light magenta": struct{}{},
		"shiny brown":   struct{}{},
	},
	"plaid olive": {
		"dim gold": struct{}{},
	},
	"plaid orange": {
		"faded red":    struct{}{},
		"muted olive":  struct{}{},
		"pale crimson": struct{}{},
		"plaid bronze": struct{}{},
		"striped gray": struct{}{},
	},
	"plaid purple": {
		"clear chartreuse": struct{}{},
		"dotted black":     struct{}{},
		"drab aqua":        struct{}{},
		"light chartreuse": struct{}{},
		"muted tan":        struct{}{},
		"plaid blue":       struct{}{},
		"vibrant tomato":   struct{}{},
	},
	"plaid salmon": {
		"dark silver":      struct{}{},
		"drab orange":      struct{}{},
		"light teal":       struct{}{},
		"mirrored magenta": struct{}{},
		"posh silver":      struct{}{},
		"striped black":    struct{}{},
		"striped cyan":     struct{}{},
	},
	"plaid tan": {
		"bright black":     struct{}{},
		"dim white":        struct{}{},
		"shiny yellow":     struct{}{},
		"vibrant lavender": struct{}{},
	},
	"plaid tomato": {
		"clear lime": struct{}{},
	},
	"plaid turquoise": {
		"dotted yellow": struct{}{},
		"vibrant red":   struct{}{},
	},
	"plaid white": {
		"mirrored turquoise": struct{}{},
	},
	"posh aqua": {
		"dotted lavender": struct{}{},
		"dotted maroon":   struct{}{},
		"posh orange":     struct{}{},
	},
	"posh beige": {
		"dotted black":    struct{}{},
		"light magenta":   struct{}{},
		"mirrored tomato": struct{}{},
		"plaid lime":      struct{}{},
		"posh black":      struct{}{},
	},
	"posh black": {
		"dark blue":     struct{}{},
		"dotted yellow": struct{}{},
	},
	"posh blue": {
		"dark tomato":   struct{}{},
		"muted brown":   struct{}{},
		"muted crimson": struct{}{},
	},
	"posh bronze": {
		"clear salmon":     struct{}{},
		"faded chartreuse": struct{}{},
		"light blue":       struct{}{},
		"posh plum":        struct{}{},
	},
	"posh brown": {
		"bright brown":    struct{}{},
		"dull orange":     struct{}{},
		"mirrored salmon": struct{}{},
		"pale gray":       struct{}{},
		"vibrant gray":    struct{}{},
	},
	"posh chartreuse": {
		"clear aqua":     struct{}{},
		"dark bronze":    struct{}{},
		"dim violet":     struct{}{},
		"muted magenta":  struct{}{},
		"posh lime":      struct{}{},
		"striped black":  struct{}{},
		"striped yellow": struct{}{},
		"vibrant beige":  struct{}{},
	},
	"posh coral": {
		"dotted silver": struct{}{},
		"posh silver":   struct{}{},
		"vibrant lime":  struct{}{},
	},
	"posh crimson": {
		"dim gray":       struct{}{},
		"muted lavender": struct{}{},
		"vibrant orange": struct{}{},
	},
	"posh cyan": {
		"bright purple": struct{}{},
	},
	"posh fuchsia": {
		"faded maroon": struct{}{},
		"pale orange":  struct{}{},
	},
	"posh gold": {
		"pale fuchsia":    struct{}{},
		"shiny maroon":    struct{}{},
		"striped fuchsia": struct{}{},
	},
	"posh gray": {
		"clear beige":    struct{}{},
		"drab turquoise": struct{}{},
		"pale coral":     struct{}{},
		"plaid black":    struct{}{},
	},
	"posh indigo": {
		"dull aqua": struct{}{},
	},
	"posh lavender": {
		"dull tomato":    struct{}{},
		"faded lavender": struct{}{},
		"posh brown":     struct{}{},
	},
	"posh lime": {
		"dark beige":  struct{}{},
		"dim violet":  struct{}{},
		"muted beige": struct{}{},
	},
	"posh maroon": {
		"mirrored crimson": struct{}{},
		"wavy white":       struct{}{},
	},
	"posh orange": {
		"dim gold":     struct{}{},
		"drab aqua":    struct{}{},
		"drab fuchsia": struct{}{},
	},
	"posh plum": {
		"dotted gray":  struct{}{},
		"shiny yellow": struct{}{},
	},
	"posh salmon": {
		"dotted fuchsia": struct{}{},
		"pale olive":     struct{}{},
		"striped aqua":   struct{}{},
	},
	"posh silver": {
		"clear beige":     struct{}{},
		"pale magenta":    struct{}{},
		"pale purple":     struct{}{},
		"striped magenta": struct{}{},
		"vibrant plum":    struct{}{},
	},
	"posh teal": {
		"wavy gray": struct{}{},
	},
	"posh tomato": {
		"mirrored violet":    struct{}{},
		"striped chartreuse": struct{}{},
	},
	"posh turquoise": {
		"bright olive": struct{}{},
		"light tan":    struct{}{},
	},
	"posh white": {
		"pale aqua": struct{}{},
	},
	"posh yellow": {
		"dotted yellow": struct{}{},
		"drab coral":    struct{}{},
		"light plum":    struct{}{},
	},
	"shiny aqua": {
		"clear crimson":  struct{}{},
		"dim tomato":     struct{}{},
		"dull cyan":      struct{}{},
		"vibrant yellow": struct{}{},
	},
	"shiny beige": {
		"dark cyan":         struct{}{},
		"dark indigo":       struct{}{},
		"dim green":         struct{}{},
		"drab tan":          struct{}{},
		"faded bronze":      struct{}{},
		"mirrored black":    struct{}{},
		"mirrored lime":     struct{}{},
		"mirrored silver":   struct{}{},
		"muted coral":       struct{}{},
		"muted tan":         struct{}{},
		"vibrant turquoise": struct{}{},
	},
	"shiny black": {
		"dark lime":   struct{}{},
		"dotted cyan": struct{}{},
		"posh beige":  struct{}{},
	},
	"shiny bronze": {
		"dotted plum":   struct{}{},
		"drab beige":    struct{}{},
		"plaid magenta": struct{}{},
		"posh fuchsia":  struct{}{},
	},
	"shiny brown": {
		"bright teal": struct{}{},
	},
	"shiny chartreuse": {
		"drab coral": struct{}{},
		"light red":  struct{}{},
	},
	"shiny coral": {
		"light olive": struct{}{},
	},
	"shiny crimson": {
		"dotted lime":     struct{}{},
		"light yellow":    struct{}{},
		"mirrored indigo": struct{}{},
		"pale chartreuse": struct{}{},
		"wavy maroon":     struct{}{},
	},
	"shiny fuchsia": {
		"bright olive":  struct{}{},
		"faded tan":     struct{}{},
		"light coral":   struct{}{},
		"striped plum":  struct{}{},
		"vibrant green": struct{}{},
	},
	"shiny gold": {
		"clear turquoise": struct{}{},
		"dull white":      struct{}{},
		"plaid gray":      struct{}{},
		"shiny salmon":    struct{}{},
		"striped green":   struct{}{},
		"wavy lime":       struct{}{},
	},
	"shiny gray": {
		"clear coral": struct{}{},
		"muted beige": struct{}{},
	},
	"shiny green": {
		"striped indigo": struct{}{},
		"striped white":  struct{}{},
	},
	"shiny indigo": {
		"bright coral":   struct{}{},
		"dark lavender":  struct{}{},
		"drab crimson":   struct{}{},
		"drab purple":    struct{}{},
		"drab silver":    struct{}{},
		"dull tan":       struct{}{},
		"light aqua":     struct{}{},
		"light indigo":   struct{}{},
		"mirrored black": struct{}{},
		"plaid lavender": struct{}{},
		"vibrant brown":  struct{}{},
	},
	"shiny lavender": {
		"dotted fuchsia": struct{}{},
		"dotted green":   struct{}{},
		"drab gray":      struct{}{},
		"drab indigo":    struct{}{},
		"wavy violet":    struct{}{},
	},
	"shiny lime": {
		"mirrored lavender": struct{}{},
		"vibrant blue":      struct{}{},
		"wavy turquoise":    struct{}{},
	},
	"shiny magenta": {
		"clear magenta":   struct{}{},
		"striped beige":   struct{}{},
		"vibrant fuchsia": struct{}{},
		"wavy gray":       struct{}{},
	},
	"shiny olive": {
		"muted gray": struct{}{},
		"wavy gold":  struct{}{},
	},
	"shiny orange": {
		"dark crimson": struct{}{},
		"dim violet":   struct{}{},
		"posh indigo":  struct{}{},
	},
	"shiny plum": {
		"faded coral": struct{}{},
	},
	"shiny purple": {
		"clear lime": struct{}{},
	},
	"shiny red": {
		"dotted gold": struct{}{},
	},
	"shiny salmon": {
		"clear gold": struct{}{},
		"dark tan":   struct{}{},
		"dim indigo": struct{}{},
	},
	"shiny silver": {
		"dim bronze": struct{}{},
	},
	"shiny teal": {
		"dark gold":   struct{}{},
		"drab yellow": struct{}{},
		"plaid cyan":  struct{}{},
		"shiny gray":  struct{}{},
	},
	"shiny tomato": {
		"clear green": struct{}{},
		"dim olive":   struct{}{},
		"dim tan":     struct{}{},
		"muted cyan":  struct{}{},
	},
	"shiny white": {
		"pale teal": struct{}{},
	},
	"shiny yellow": {
		"pale aqua":       struct{}{},
		"posh tan":        struct{}{},
		"striped maroon":  struct{}{},
		"wavy chartreuse": struct{}{},
	},
	"striped beige": {
		"plaid olive": struct{}{},
	},
	"striped black": {
		"dark beige": struct{}{},
		"dull olive": struct{}{},
		"faded blue": struct{}{},
		"posh black": struct{}{},
	},
	"striped blue": {
		"dark gray":     struct{}{},
		"dotted yellow": struct{}{},
		"pale lavender": struct{}{},
		"posh crimson":  struct{}{},
	},
	"striped bronze": {
		"light blue": struct{}{},
	},
	"striped brown": {
		"bright gray":       struct{}{},
		"dark orange":       struct{}{},
		"dim coral":         struct{}{},
		"dim white":         struct{}{},
		"drab olive":        struct{}{},
		"light chartreuse":  struct{}{},
		"pale gold":         struct{}{},
		"shiny crimson":     struct{}{},
		"striped lavender":  struct{}{},
		"vibrant brown":     struct{}{},
		"vibrant tan":       struct{}{},
		"vibrant turquoise": struct{}{},
	},
	"striped coral": {
		"bright bronze": struct{}{},
		"bright salmon": struct{}{},
		"shiny tan":     struct{}{},
	},
	"striped crimson": {
		"dull aqua": struct{}{},
	},
	"striped fuchsia": {
		"vibrant red": struct{}{},
	},
	"striped gold": {
		"pale silver": struct{}{},
		"shiny olive": struct{}{},
	},
	"striped green": {
		"dull gray":   struct{}{},
		"pale indigo": struct{}{},
		"pale tan":    struct{}{},
		"plaid blue":  struct{}{},
		"posh salmon": struct{}{},
		"shiny gray":  struct{}{},
	},
	"striped indigo": {
		"dull black": struct{}{},
	},
	"striped lavender": {
		"dim tan":        struct{}{},
		"posh turquoise": struct{}{},
	},
	"striped magenta": {
		"wavy purple": struct{}{},
	},
	"striped olive": {
		"bright crimson":   struct{}{},
		"mirrored crimson": struct{}{},
		"wavy maroon":      struct{}{},
	},
	"striped orange": {
		"clear tan":          struct{}{},
		"drab brown":         struct{}{},
		"mirrored white":     struct{}{},
		"muted crimson":      struct{}{},
		"vibrant chartreuse": struct{}{},
		"wavy teal":          struct{}{},
	},
	"striped red": {
		"dull turquoise": struct{}{},
		"light yellow":   struct{}{},
		"wavy tomato":    struct{}{},
	},
	"striped salmon": {
		"dim salmon": struct{}{},
	},
	"striped silver": {
		"clear tan":      struct{}{},
		"dim crimson":    struct{}{},
		"muted lavender": struct{}{},
	},
	"striped tan": {
		"clear tomato":   struct{}{},
		"plaid coral":    struct{}{},
		"striped tomato": struct{}{},
		"vibrant teal":   struct{}{},
		"wavy green":     struct{}{},
	},
	"striped violet": {
		"dotted tan":      struct{}{},
		"mirrored yellow": struct{}{},
	},
	"striped white": {
		"dull violet": struct{}{},
	},
	"striped yellow": {
		"drab purple":    struct{}{},
		"drab tomato":    struct{}{},
		"faded lavender": struct{}{},
		"faded tomato":   struct{}{},
		"plaid maroon":   struct{}{},
		"shiny coral":    struct{}{},
	},
	"vibrant beige": {
		"drab orange":     struct{}{},
		"vibrant fuchsia": struct{}{},
	},
	"vibrant blue": {
		"bright magenta":  struct{}{},
		"wavy chartreuse": struct{}{},
	},
	"vibrant bronze": {
		"drab white": struct{}{},
	},
	"vibrant brown": {
		"bright beige":     struct{}{},
		"clear plum":       struct{}{},
		"dotted coral":     struct{}{},
		"drab red":         struct{}{},
		"drab teal":        struct{}{},
		"muted plum":       struct{}{},
		"pale blue":        struct{}{},
		"pale yellow":      struct{}{},
		"striped green":    struct{}{},
		"vibrant lavender": struct{}{},
		"vibrant white":    struct{}{},
		"wavy red":         struct{}{},
	},
	"vibrant chartreuse": {
		"light teal":     struct{}{},
		"posh tomato":    struct{}{},
		"posh turquoise": struct{}{},
	},
	"vibrant coral": {
		"bright blue":   struct{}{},
		"bright silver": struct{}{},
		"clear cyan":    struct{}{},
		"dark tomato":   struct{}{},
		"light cyan":    struct{}{},
		"light green":   struct{}{},
		"plaid orange":  struct{}{},
		"posh blue":     struct{}{},
		"vibrant olive": struct{}{},
		"vibrant tan":   struct{}{},
	},
	"vibrant crimson": {
		"bright yellow": struct{}{},
		"wavy white":    struct{}{},
	},
	"vibrant cyan": {
		"plaid coral": struct{}{},
	},
	"vibrant gold": {
		"striped indigo": struct{}{},
	},
	"vibrant gray": {
		"bright chartreuse": struct{}{},
		"faded lime":        struct{}{},
		"mirrored orange":   struct{}{},
		"shiny plum":        struct{}{},
	},
	"vibrant lavender": {
		"muted blue":  struct{}{},
		"pale silver": struct{}{},
	},
	"vibrant magenta": {
		"dull olive":    struct{}{},
		"muted orange":  struct{}{},
		"shiny bronze":  struct{}{},
		"vibrant black": struct{}{},
	},
	"vibrant maroon": {
		"faded gold":  struct{}{},
		"wavy tomato": struct{}{},
	},
	"vibrant orange": {
		"dim blue":    struct{}{},
		"dull yellow": struct{}{},
	},
	"vibrant plum": {
		"clear gray":   struct{}{},
		"dark salmon":  struct{}{},
		"shiny yellow": struct{}{},
	},
	"vibrant silver": {
		"drab yellow":  struct{}{},
		"muted tomato": struct{}{},
	},
	"vibrant tan": {
		"bright coral": struct{}{},
		"dark plum":    struct{}{},
		"drab teal":    struct{}{},
		"pale yellow":  struct{}{},
		"posh aqua":    struct{}{},
	},
	"vibrant teal": {
		"clear yellow": struct{}{},
	},
	"vibrant turquoise": {
		"dotted salmon": struct{}{},
		"plaid brown":   struct{}{},
	},
	"vibrant violet": {
		"light cyan": struct{}{},
		"muted gray": struct{}{},
	},
	"vibrant white": {
		"clear purple":   struct{}{},
		"dotted coral":   struct{}{},
		"dotted tomato":  struct{}{},
		"faded beige":    struct{}{},
		"light tan":      struct{}{},
		"mirrored blue":  struct{}{},
		"striped violet": struct{}{},
	},
	"vibrant yellow": {
		"dim fuchsia": struct{}{},
		"drab green":  struct{}{},
		"faded blue":  struct{}{},
		"light gray":  struct{}{},
	},
	"wavy beige": {
		"dotted blue":  struct{}{},
		"drab maroon":  struct{}{},
		"wavy crimson": struct{}{},
	},
	"wavy blue": {
		"muted silver": struct{}{},
	},
	"wavy bronze": {
		"bright violet":    struct{}{},
		"clear chartreuse": struct{}{},
		"plaid salmon":     struct{}{},
	},
	"wavy coral": {
		"bright gold":   struct{}{},
		"dim silver":    struct{}{},
		"dull gray":     struct{}{},
		"faded black":   struct{}{},
		"faded violet":  struct{}{},
		"faded yellow":  struct{}{},
		"light aqua":    struct{}{},
		"striped gray":  struct{}{},
		"striped green": struct{}{},
		"vibrant cyan":  struct{}{},
	},
	"wavy gold": {
		"striped salmon": struct{}{},
	},
	"wavy gray": {
		"dim lime":     struct{}{},
		"faded salmon": struct{}{},
		"plaid aqua":   struct{}{},
	},
	"wavy green": {
		"posh indigo":     struct{}{},
		"striped fuchsia": struct{}{},
	},
	"wavy indigo": {
		"dark purple":        struct{}{},
		"drab coral":         struct{}{},
		"mirrored turquoise": struct{}{},
		"wavy brown":         struct{}{},
	},
	"wavy lavender": {
		"bright violet":     struct{}{},
		"clear tan":         struct{}{},
		"drab magenta":      struct{}{},
		"dull beige":        struct{}{},
		"light silver":      struct{}{},
		"mirrored lavender": struct{}{},
		"pale gray":         struct{}{},
		"pale yellow":       struct{}{},
		"vibrant beige":     struct{}{},
	},
	"wavy lime": {
		"dull bronze":   struct{}{},
		"vibrant beige": struct{}{},
	},
	"wavy maroon": {
		"bright plum":     struct{}{},
		"dotted brown":    struct{}{},
		"dull chartreuse": struct{}{},
		"faded white":     struct{}{},
		"pale teal":       struct{}{},
	},
	"wavy olive": {
		"dim cyan": struct{}{},
	},
	"wavy orange": {
		"mirrored chartreuse": struct{}{},
	},
	"wavy red": {
		"bright gold":      struct{}{},
		"bright white":     struct{}{},
		"dim beige":        struct{}{},
		"dotted teal":      struct{}{},
		"drab lavender":    struct{}{},
		"shiny chartreuse": struct{}{},
	},
	"wavy salmon": {
		"dull purple":  struct{}{},
		"pale cyan":    struct{}{},
		"plaid tomato": struct{}{},
	},
	"wavy teal": {
		"drab aqua":  struct{}{},
		"dull black": struct{}{},
		"wavy blue":  struct{}{},
	},
	"wavy tomato": {
		"muted salmon": struct{}{},
	},
	"wavy turquoise": {
		"pale cyan":       struct{}{},
		"pale indigo":     struct{}{},
		"striped fuchsia": struct{}{},
	},
	"wavy violet": {
		"clear gold":  struct{}{},
		"muted coral": struct{}{},
	},
	"wavy white": {
		"muted tomato": struct{}{},
	},
	"wavy yellow": {
		"dull purple": struct{}{},
		"pale purple": struct{}{},
	},
}
